### Numpy Array : Indexing and Selection

In [77]:
import numpy as np

In [92]:
L = np.arange(1,20,2)
L

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [79]:
L[0]

1

In [80]:
L[1]

3

In [81]:
L[-1]

19

In [82]:
L[0:3]

array([1, 3, 5])

In [83]:
L[:3]

array([1, 3, 5])

In [85]:
L[3:]

array([ 7,  9, 11, 13, 15, 17, 19])

### Broadcasting

In [95]:
L1 = np.arange(1,25,3)
L1

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [97]:
L1[0:3] =20
L1

array([20, 20, 20, 10, 13, 16, 19, 22])

In [103]:
L2 = np.arange(1,20)
L2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [104]:
slice_L2 = L2[0:3].copy()

In [105]:
slice_L2

array([1, 2, 3])

In [112]:
slice_L2[:] = 20
slice_L2

array([20, 20, 20])

In [113]:
L2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

### 2D array

In [115]:
my_2D = np.array([[1,2,3],[3,6,9],[1,5,7]])
my_2D

array([[1, 2, 3],
       [3, 6, 9],
       [1, 5, 7]])

In [116]:
my_2D.shape

(3, 3)

In [117]:
my_2D[0][0]

1

In [118]:
my_2D[0,0]

1

In [119]:
my_2D

array([[1, 2, 3],
       [3, 6, 9],
       [1, 5, 7]])

In [120]:
my_2D[0]

array([1, 2, 3])

In [121]:
my_2D[-1]

array([1, 5, 7])

In [122]:
my_2D[:,-1]

array([3, 9, 7])

In [123]:
my_2D

array([[1, 2, 3],
       [3, 6, 9],
       [1, 5, 7]])

In [124]:
my_2D[0:2,0:2]

array([[1, 2],
       [3, 6]])

### Conditional selection 

In [128]:
L3 = np.arange(0,20,3)
L3

array([ 0,  3,  6,  9, 12, 15, 18])

In [129]:
L3[L3>6]

array([ 9, 12, 15, 18])

In [130]:
L3>6

array([False, False, False,  True,  True,  True,  True])

### Numpy operations : Mathematics and Statistics 

In [165]:
L1 = np.arange(0,5)
L1

array([0, 1, 2, 3, 4])

In [166]:
L1+5

array([5, 6, 7, 8, 9])

In [167]:
L1-5

array([-5, -4, -3, -2, -1])

In [168]:
L1*5

array([ 0,  5, 10, 15, 20])

In [169]:
L1/5

array([0. , 0.2, 0.4, 0.6, 0.8])

In [170]:
L2 = np.arange(0,10,2)
L2

array([0, 2, 4, 6, 8])

In [171]:
L1.shape

(5,)

In [172]:
L2.shape

(5,)

In [173]:
L1+L2

array([ 0,  3,  6,  9, 12])

In [175]:
L1*L2

array([ 0,  2,  8, 18, 32])

In [176]:
L1/L2

C:\Users\mrcfi\anaconda3\envs\python-cvcourse\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, 0.5, 0.5, 0.5, 0.5])

In [177]:
0/0

ZeroDivisionError: division by zero

In [178]:
5/L1

C:\Users\mrcfi\anaconda3\envs\python-cvcourse\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 5.        , 2.5       , 1.66666667, 1.25      ])

In [179]:
5/0

ZeroDivisionError: division by zero

In [180]:
np.sqrt(L1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [181]:
L1

array([0, 1, 2, 3, 4])

In [182]:
np.cos(L1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [183]:
np.exp(L1)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

### Statistics

In [184]:
L1.max()

4

In [185]:
L1.min()

0

In [186]:
L1.sum()

10

In [187]:
L1

array([0, 1, 2, 3, 4])

In [188]:
L1.var()

2.0

In [191]:
L1.std()

1.4142135623730951

In [192]:
my_2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [195]:
my_2D.sum()

120

In [196]:
my_2D.sum(axis=0)

array([24, 28, 32, 36])

In [197]:
my_2D.mean(axis=0)

array([6., 7., 8., 9.])