### Python list

In [4]:
L1 = [1,2,3]
L1

[1, 2, 3]

In [5]:
L2 = [3,6,9]
L2

[3, 6, 9]

In [7]:
# L1*L2

In [8]:
import numpy as np

### Numpy arrays from python lists

In [9]:
L1 = np.array(L1)
L1

array([1, 2, 3])

In [10]:
L2 = np.array(L2)
L2

array([3, 6, 9])

In [11]:
L1*L2

array([ 3, 12, 27])

In [12]:
list_2D = [[1,2,3],[2,4,6],[1,6,9]]
list_2D

[[1, 2, 3], [2, 4, 6], [1, 6, 9]]

In [13]:
my_2D = np.array(list_2D)
my_2D

array([[1, 2, 3],
       [2, 4, 6],
       [1, 6, 9]])

### Dimension and Shape

In [14]:
L1.ndim

1

In [15]:
my_2D.ndim

2

In [16]:
L1.shape

(3,)

In [17]:
my_2D.shape

(3, 3)

In [20]:
a = np.array([1,3,6])
b = a.copy()
b[0] = 0
a

array([1, 3, 6])

### Data Type

In [21]:
L1.dtype

dtype('int32')

In [23]:
L3 = np.array([0.1,0.3])
L3

array([0.1, 0.3])

In [24]:
L3.dtype

dtype('float64')

### Built-in functions

### arange

In [32]:
np.arange(0,10,3)

array([0, 3, 6, 9])

### zeros and ones

In [33]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [39]:
np.ones((2,3))*4

array([[4., 4., 4.],
       [4., 4., 4.]])

### linspace

In [43]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### eye

In [45]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Random number generator 

#### rand, randn, randint

In [47]:
np.random.rand(5)

array([0.63834991, 0.52106544, 0.9255438 , 0.40984883, 0.2466223 ])

In [48]:
np.random.rand(5,3)

array([[0.97214448, 0.96532796, 0.68095988],
       [0.44801974, 0.83612944, 0.68955545],
       [0.71921859, 0.31205548, 0.91490739],
       [0.86914975, 0.43468624, 0.66301923],
       [0.25988258, 0.82875436, 0.68522374]])

In [49]:
np.random.randn(5)

array([ 1.23107966,  1.12243013,  0.82358742, -1.61239562,  0.25672643])

In [50]:
np.random.randn(4,3)

array([[-0.67352858,  1.11423319,  2.44480087],
       [-1.43639852, -0.6705568 ,  1.4027918 ],
       [-2.37181906,  2.29734742, -0.97508118],
       [ 0.46071174, -0.18675389,  1.40019833]])

In [54]:
np.random.randint(0,10, 15)

array([3, 6, 8, 7, 4, 9, 1, 3, 6, 1, 4, 8, 3, 9, 8])

In [55]:
np.random.randint(1,50,(3,4))

array([[31, 37, 22, 41],
       [42, 24, 47, 28],
       [22, 47,  7, 12]])

### seed

In [68]:
np.random.seed(15)
np.random.rand(5)

array([0.8488177 , 0.17889592, 0.05436321, 0.36153845, 0.27540093])

In [75]:
np.random.rand(5)

array([0.64272489, 0.41998182, 0.40324243, 0.39042033, 0.40618952])

### Attributes 

In [76]:
L1 = np.arange(36)
L1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [79]:
L1.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

### min and max and thier location

In [80]:
L1 = np.random.randint(0,50,10)
L1

array([46, 12, 33,  2, 24, 44, 42, 17, 23, 29])

In [81]:
L1.max()

46

In [82]:
L1.min()

2

In [83]:
L1.argmax()

0

In [92]:
L1.argmin()

3